version: '3.4'

services:
  webapplication3:
    image: ${DOCKER_REGISTRY-}webapplication3
    build:
      context: .
      dockerfile: WebApplication3/Dockerfile
    ports:
      - "8080:8080"
      - "44349:443"
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=https://+:443;http://+:80
       - ASPNETCORE_Kestrel__Certificates__Default__Password=Pass@*****
       - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/dockerdemo.pfx
    depends_on:
      - "sql_server"
  sql_server:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: '41da!dse1@2'
    ports:
      - "1433:1433"