version: '3.4'

services:
  webapplication3:
    image: ${DOCKER_REGISTRY-}webapplication3
    build:
      context: .
      dockerfile: WebApplication3/Dockerfile
    depends_on:
      - "sql_server"
  sql_server:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: '41da!dse1@2'
      ACCEPT_EULA: 'Y'
    ports:
      - "1433:1433"