version: '3.4'

services:
  webapplication3:
    image: ${DOCKER_REGISTRY-}webapplication3
    build:
      context: .
      dockerfile: WebApplication3/Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - /etc/nginx/sites-available/3220911-ew88386.twc1:/etc/nginx/conf.d/default.conf
      - ~/.aspnet/https:/https:ro
    depends_on:
      - "sql_server"
  sql_server:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: '41da!dse1@2'
    ports:
      - "1433:1433"

